inp1=eval(input("Enter the first number:"))
inp2=eval(input("Enter the second number:"))
print("The arithametic operation are as follows:")
print(inp1,"+",inp2,"=",inp1+inp2)
print(inp1,"-",inp2,"=",inp1-inp2)
print(inp1,"*",inp2,"=",inp1*inp2)
print(inp1,"/",inp2,"=",inp1/inp2)
print(inp1,"//",inp2,"=",inp1//inp2)
print(inp1,"%",inp2,"=",inp1%inp2)